"""Add booking status

Revision ID: 0f95423c7d44
Revises: 098710b47af1
Create Date: 2025-08-28 03:34:40.255080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f95423c7d44'
down_revision: Union[str, Sequence[str], None] = '098710b47af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE bookingstatus AS ENUM ('PENDING_DEPOSIT', 'CONFIRMED', 'CANCELLED')")
    op.add_column('bookings', sa.Column('status', sa.Enum('PENDING_DEPOSIT', 'CONFIRMED', 'CANCELLED', name='bookingstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'status')
    op.execute("DROP TYPE bookingstatus")
    # ### end Alembic commands ###